- .github/workflows/build.yml
- scripts/build.sh
> #174 Use upload-artefacts action in build workflow

- src/components/panels/details/interchange-card.tsx
- src/components/panels/details/interchange-field.tsx
- src/components/svgs/stations/gzmtr-int.tsx
- src/components/svgs/stations/mtr.tsx
- src/components/svgs/stations/shmetro-basic-2020.tsx
- src/components/svgs/stations/stations.ts
- src/constants/stations.ts
- src/i18n/translations/en.json
- src/i18n/translations/ko.json
- src/i18n/translations/zh-Hans.json
- src/i18n/translations/zh-Hant.json
- src/util/save.test.ts
- src/util/save.ts
> #224 MTR station

- src/components/page-header/settings-modal.tsx
- src/components/svg-wrapper.tsx
- src/util/helpers.ts
> #306 Add mac shortcuts in settings

- src/util/rmg-param-parser.ts
> #315 Update RMG import parser

- src/components/page-header/procedures-modal.tsx
- src/components/page-header/settings-modal.tsx
- src/util/to-rmg.ts
> Generate RMG saves (merge to repo)

- src/components/page-header/rmg-param-app-clip.tsx
> Update RMG import app clip url to support Tauri

- src/components/panels/details/color-field.tsx
- src/components/panels/details/details.tsx
- src/components/panels/details/info-multiple-selection.tsx
- src/components/panels/details/info-section.tsx
- src/components/panels/details/interchange-field.tsx
- src/components/panels/details/line-extremities-section.tsx
- src/components/panels/details/line-type-section.tsx
- src/components/panels/details/node-position-section.tsx
- src/components/panels/details/rmg-field-specific-attrs.tsx
- src/components/panels/details/specific-attrs.tsx
- src/components/panels/details/station-type-section.tsx
- src/components/svg-canvas-graph.tsx
- src/components/svg-wrapper.tsx
- src/components/svgs/lines/styles/dual-color.tsx
- src/constants/constants.ts
- src/redux/index.ts
- src/redux/runtime/runtime-slice.ts
- src/util/clipboard.ts
> #534 Convert selected to Set<string>

- src/components/svg-canvas-graph.tsx
- src/components/svg-wrapper.tsx
> #320 Fix unexpected multiple selection

- src/components/panels/details/rmg-field-specific-attrs.tsx
- src/components/svgs/lines/line-wrapper.tsx
> #558 Advanced auto simple path

- public/styles/fonts_jreast.css
- src/components/svg-wrapper.tsx
- src/components/svgs/common/multiline-text-vertical.tsx
- src/components/svgs/common/multiline-text.tsx
- src/components/svgs/stations/jr-east-basic.tsx
- src/components/svgs/stations/jr-east-important.tsx
- src/components/svgs/stations/stations.ts
- src/components/svgs/stations/suzhourt-int.tsx
- src/constants/stations.ts
- src/i18n/translations/en.json
- src/i18n/translations/ja.json
- src/i18n/translations/ko.json
- src/i18n/translations/zh-Hans.json
- src/i18n/translations/zh-Hant.json
- src/util/download.ts
- src/util/fonts.ts
> #557 JR East stations

- src/components/svgs/nodes/jr-east-line-badge.tsx
- src/components/svgs/nodes/misc-nodes.ts
- src/components/svgs/nodes/shmetro-text-line-badge.tsx
- src/constants/nodes.ts
- src/i18n/translations/en.json
- src/i18n/translations/ja.json
- src/i18n/translations/ko.json
- src/i18n/translations/zh-Hans.json
- src/i18n/translations/zh-Hant.json
- src/util/fonts.ts
> #567 JR East line badge

- src/components/svgs/common/unknown.tsx
- src/components/svgs/lines/line-wrapper.tsx
- src/components/svgs/lines/lines.ts
- src/components/svgs/lines/paths/diagonal.tsx
- src/components/svgs/lines/paths/perpendicular.tsx
- src/components/svgs/lines/paths/rotate-perpendicular.tsx
- src/components/svgs/lines/paths/simple.tsx
- src/components/svgs/lines/styles/bjsubway-dotted.tsx
- src/components/svgs/lines/styles/bjsubway-single-color.tsx
- src/components/svgs/lines/styles/dual-color.tsx
- src/components/svgs/lines/styles/jr-east-single-color-pattern.tsx
- src/components/svgs/lines/styles/jr-east-single-color.tsx
- src/constants/lines.ts
- src/i18n/translations/en.json
- src/i18n/translations/ja.json
- src/i18n/translations/ko.json
- src/i18n/translations/zh-Hans.json
- src/i18n/translations/zh-Hant.json
- src/util/bezier-parallel.ts
- src/util/pathRounding.js
- src/util/reconcile.ts
> #563 JR East single color (pattern) line style

- src/components/svgs/common/multiline-text-vertical.tsx
- src/components/svgs/common/multiline-text.tsx
- src/components/svgs/stations/jr-east-basic.tsx
> #581 Better name offset of JR East stations in rotation

- src/components/page-header/donation-modal.tsx
> #625 Update and fix incorrect links to RMP Gallery

- src/components/page-header/search-popover.tsx
- src/components/page-header/window-header.tsx
- src/i18n/translations/en.json
- src/i18n/translations/ja.json
- src/i18n/translations/ko.json
- src/i18n/translations/zh-Hans.json
- src/i18n/translations/zh-Hant.json
> #635 Search stations

- src/util/change-types.ts
> #654 Match the name length when changing station type

- src/components/page-header/procedures/change-type-modal.tsx
- src/i18n/translations/en.json
- src/i18n/translations/ja.json
- src/i18n/translations/ko.json
- src/i18n/translations/zh-Hans.json
- src/i18n/translations/zh-Hant.json
- src/util/change-types.ts
> #738 Change zIndex in batch

- src/components/svgs/nodes/qingdao-metro-num-line-badge.tsx
- src/components/svgs/stations/qingdao-metro-station.tsx
- src/constants/stations.ts
- src/util/change-types.ts
> #742 Change station type keeping color

- src/components/svg-canvas-graph.tsx
- src/components/svg-wrapper.tsx
- src/components/svgs/common/unknown.tsx
- src/components/svgs/lines/line-wrapper.tsx
- src/components/svgs/lines/styles/bjsubway-dotted.tsx
- src/components/svgs/lines/styles/bjsubway-single-color.tsx
- src/components/svgs/lines/styles/bjsubway-tram.tsx
- src/components/svgs/lines/styles/china-railway.tsx
- src/components/svgs/lines/styles/dual-color.tsx
- src/components/svgs/lines/styles/gzmtr-virtual-int.tsx
- src/components/svgs/lines/styles/jr-east-single-color-pattern.tsx
- src/components/svgs/lines/styles/jr-east-single-color.tsx
- src/components/svgs/lines/styles/mrt-sentosa-express.tsx
- src/components/svgs/lines/styles/mrt-under-construction.tsx
- src/components/svgs/lines/styles/mtr-light-rail.tsx
- src/components/svgs/lines/styles/mtr-paid-area.tsx
- src/components/svgs/lines/styles/mtr-race-day.tsx
- src/components/svgs/lines/styles/mtr-unpaid-area.tsx
- src/components/svgs/lines/styles/river.tsx
- src/components/svgs/lines/styles/shmetro-virtual-int.tsx
- src/components/svgs/lines/styles/single-color.tsx
- src/constants/lines.ts
> #753 Add station in a current line

- src/components/svgs/lines/styles/dual-color.tsx
- src/i18n/translations/en.json
- src/i18n/translations/ja.json
- src/i18n/translations/ko.json
- src/i18n/translations/zh-Hans.json
- src/i18n/translations/zh-Hant.json
> #815 Dual color line style

- src/util/fonts.ts
> #821 Fix MTR fonts loading issue

- src/components/svgs/lines/lines.ts
- src/components/svgs/lines/styles/shanghai-suburban-railway.tsx
- src/components/svgs/stations/shanghai-suburban-railway.tsx
- src/components/svgs/stations/shmetro-basic-2020.tsx
- src/components/svgs/stations/shmetro-basic.tsx
- src/components/svgs/stations/shmetro-int.tsx
- src/components/svgs/stations/shmetro-osysi.tsx
- src/components/svgs/stations/stations.ts
- src/constants/lines.ts
- src/constants/stations.ts
- src/i18n/translations/en.json
- src/i18n/translations/ja.json
- src/i18n/translations/ko.json
- src/i18n/translations/zh-Hans.json
- src/i18n/translations/zh-Hant.json
- src/util/change-types.ts
> #831 Shanghai Suburban Railway style

- package-lock.json
- package.json
- src/components/page-header/master-import.tsx
- src/components/page-header/master-manager.tsx
- src/components/svgs/nodes/master.tsx
- src/constants/master.ts
- src/i18n/translations/en.json
- src/i18n/translations/ja.json
- src/i18n/translations/ko.json
- src/i18n/translations/zh-Hans.json
- src/i18n/translations/zh-Hant.json
- src/util/helpers.ts
> #860 Import master node param from designer and gallery directly

- src/components/page-header/master-import.tsx
> #877 Fix loading param to master node from designer and gallery

- src/components/svgs/lines/lines.ts
- src/components/svgs/lines/styles/gzmtr-loop.tsx
- src/constants/lines.ts
- src/i18n/translations/en.json
- src/i18n/translations/ja.json
- src/i18n/translations/ko.json
- src/i18n/translations/zh-Hans.json
- src/i18n/translations/zh-Hant.json
> #906 Guangzhou Metro loop line style

- src/components/svgs/stations/gzmtr-int.tsx
> #891 Update gzmtr int to the same scale as 2024
